### ISSUE TITLE
Wrong Formatting For Dot Delimiter (instead of Comma)

### ISSUE THREAD

**Issue by yesidlazaro** [aldoKelvianto/AutoFormatEditText#1]
hi, 

i start using your library for one project, it was working fine until i test the app in a samsung s3 mini with android 4.2.2 , the issue happens when i write a number with more that 3 digits, so if i type "2000" I expecting "2,000" but in this device the result is "2.000" yes with point instead a coma. it works fine on android 5(moto E) and android 6(nexus 5) but not in jelly bean.
here how i am using the view

`<com.aldoapps.autoformatedittext.AutoFormatEditText
                                android:id="@+id/upload_product_price"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:hint="@string/hint_price"
                                android:maxLength="14"
                                android:minWidth="@dimen/price_input_min_width"
                                app:isDecimal="true" />`

and here is a video 
https://goo.gl/photos/YzhdJ47Le4vub3BN7

thanks in advance .

**Comment by aldoKelvianto** [comment]
Hi there,
So, this library use your device locale. Have you check your device locale to EN_US ? For some country like Indonesia it uses dot instead of comma.
Thanks 

```
On Wednesday, September 21, 2016 10:07 PM, Yesid <notifications@github.com> wrote:
```

 hi,i start using your library for one project, it was working fine until i test the app in a samsung s3 mini with android 4.2.2 , the issue happens when i write a number with more that 3 digits, so if i type "2000" I expecting "2,000" but in this device the result is "2.000" yes with point instead a coma. it works fine on android 5(moto E) and android 6(nexus 5) but not in jelly bean.
here how i am using the view<com.aldoapps.autoformatedittext.AutoFormatEditText
 android:id="@+id/upload_product_price"
 android:layout_width="match_parent"
 android:layout_height="wrap_content"
 android:hint="@string/hint_price"
 android:maxLength="14"
 android:minWidth="@dimen/price_input_min_width"
 app:isDecimal="true" />and here is a video 
https://goo.gl/photos/YzhdJ47Le4vub3BN7thanks in advance .—

**Comment by aldoKelvianto** [comment]
From that video, it seems like you're using Spanish in that device. According to [this link](http://trigeminal.fmsinc.com/samples/setlocalesample2.asp) Spanish use dot instead of comma. In order to fix that you need to add second parameter to DecimalFormat in AutoFormatUtil.

```
    public static String formatToStringWithoutDecimal(double value) {
        NumberFormat formatter = new DecimalFormat(FORMAT_NO_DECIMAL, getDecimalFormatSymbol());
        return formatter.format(value);
    }

// force Spanish locale to use US Locale (comma instead of dot)
    public static DecimalFormatSymbols getDecimalFormatSymbol() {
        DecimalFormatSymbols decimalFormatSymbols = new DecimalFormatSymbols(Locale.US);
        decimalFormatSymbols.setDecimalSeparator('.');
        decimalFormatSymbols.setGroupingSeparator(',');
        return decimalFormatSymbols;
    }
```

Hope this helps!

**Comment by kalvian1060** [comment]
hai mas @aldoKelvianto  saya coba terapkan liblary in dan menggukana us format hasilnya di editext tetap menggukana ,  bukan titik.   bagaian mana yang harus dirubah?? terima kasih sebelumnya

**Comment by aldoKelvianto** [comment]
@kalvian1060 justru kalau mau pake titik Localenya harus diganti dengan negara yg pake titik, misalnya Indonesia. US itu make comma separated buat currencynya. Atau ada yang saya salah tangkap?

**Comment by kalvian1060** [comment]
maksudnya kode yang ini ?? 
DecimalFormatSymbols(Locale.US) --> kita ganti indonesia?

**Comment by aldoKelvianto** [comment]
hai @kalvian1060 justru kalau mau pake titik Localenya harus diganti dengan negara yg pake titik, misalnya Indonesia. US itu make koma buat currencynya, misalnya `1,000,000` dollar. Kalau Indonesia kan `1.000.000` rupiah. Atau ada yang saya salah tangkap?

**Comment by kalvian1060** [comment]
jadi bagaimana format Locale yang benar??

**Comment by kalvian1060** [comment]
kalau untuk text saya menggunakan format seperti ini
`DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        String hasil = kursIndonesia.format(Rupiah);`

**Comment by kalvian1060** [comment]
tapi belum berhasil

**Comment by aldoKelvianto** [comment]
Iya @kalvian1060 sayangnya ga ada `Locale.ID` untuk negara Indonesia, kita harus bikin Locale sendiri seperti `Locale locale = new Locale("in");`

Jadi, implementasinya seperti ini:
```java
Locale indoLocale = new Locale("in");
DecimalFormatSymbols decimalFormatSymbols = new DecimalFormatSymbols(indoLocale);
```

**Comment by kalvian1060** [comment]
terima kasih atas balasanya...
` public static DecimalFormatSymbols getDecimalFormatSymbol() {
        Locale indoLocale = new Locale("in");
        DecimalFormatSymbols decimalFormatSymbols = new DecimalFormatSymbols(indoLocale);
        decimalFormatSymbols.setDecimalSeparator('.');
        decimalFormatSymbols.setGroupingSeparator('.');
        return decimalFormatSymbols;
    }`

hasil akhir code seperti diatas...sekarang saya build. Nanti saya berikan komentas tentang hasilnya.. mas @aldoKelvianto

**Comment by kalvian1060** [comment]
mas @aldoKelvianto  saya coba lagi..masih belum fix

**Comment by kalvian1060** [comment]
@aldoKelvianto  dengan menambahkan Locale sekarang sudah berubah jadi .
tapi problem barunya... saat ketik 7000 menjadi 7.000  (SUKSES) tapi saat ketik 7.00000 tidak bisa format otomatis. apakah bagian ### perlu di rubah?

**Comment by aldoKelvianto** [comment]
Nanti malam saya cek lagi ya @kalvian1060

**Comment by kalvian1060** [comment]
@aldoKelvianto  oke di tunggu..maaf merepotkan

**Comment by kalvian1060** [comment]
mas @aldoKelvianto  saya sudah coba buat locale jadi 
in_ID
in
id_ID
id 

untuk format indonesia belum berhasil ?? untuk merubah jadi .

**Comment by aldoKelvianto** [comment]
@kalvian1060 @yesidlazaro Please check these updated gist for using dot instead of comma:
https://gist.github.com/aldoKelvianto/d922cb739594da946ee57096996d44e7
https://gist.github.com/aldoKelvianto/9b86f0b1ce7f6367c9a1e3a8745b0fa1

**Comment by kalvian1060** [comment]
Oke menuju TKP..thanks

**Comment by aldoKelvianto** [comment]
Oke @kalvian1060 , let me know if it works (or not) yaa

**Comment by kalvian1060** [comment]
it works 1000% . you save my live

**Comment by kalvian1060** [comment]
mas @aldoKelvianto  kalau di framework lain..setelah editext di format nanti bisa diambil seperti ini hasilnya
Getting text

maskedEditText.getUnmaskedText() //return unmasked text
maskedEditText.getText()         //return mask and text

kalau liblary ini untuk mengambil text seperti apa?? kalau saya menggunakan replace manua..tanda . pada hasil inputkan

**Comment by aldoKelvianto** [comment]
masket / unmasked itu bukannya untuk ngambil value untuk password ya?

anyway, bisa jadi masukan untuk release berikutnya.. Harusnya tinggal override method ini di `AutoFormatEditText.java`

```java

    @Override
    public Editable getText() {
        Editable editable = super.getText();
        editable.toString().replaceAll(".", "").replaceAll(",", "");
        return editable;
    }
```
Cuma belum saya tes.. Coba dulu aja @kalvian1060

**Comment by kalvian1060** [comment]
`
    private double parsingHasilEditext(String msg){
        double uang = 0;
        try {
            String uang1 = msg.replace(".", "");
            String uang2 = uang1.replaceAll("\\s+", "");

            try {
                Log.e("PARSING", uang2);
                uang = Double.parseDouble(uang2);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }catch (Exception e){
            e.printStackTrace();
        }

        return  uang;

    }`

**Comment by kalvian1060** [comment]
ini methodku untuk parsing manual...aku ovveride getText().. trus terpakan seperti diatas...
tanda . (dot) belum hilang
