### ISSUE TITLE
Cursor position goes wrong, when user deletes a digit with comma in EditText

### ISSUE THREAD

**Issue by mkaarthick** [aldoKelvianto/AutoFormatEditText#2]
1.In `EditText`, type in 12345 (It will display as 12,345)
2. Move the Cursor next to "4" and delete 4 (it will now display as 1,23|5)
3. Type a decimal point, it will now display as 123.5|, the cursor jumped one position to be behind the "5"
4. Expected output should be 123.|5

**Comment by aldoKelvianto** [comment]
@mkaarthick confirmed. I just tested it. I'll fix it as soon as possible.

**Comment by aldoKelvianto** [comment]
@mkaarthick I just fix the bug in the last commit. However, I didn't publish it to mavenCentral / jCenter just yet.

**Comment by mkaarthick** [comment]
@aldoKelvianto Thanks. That fixes the issue. Now some more issue is happening.

**Issue 1:**
Type 123, now type a decimal point. (It will display as 123|.) Continue typing some digits, you'll notice it.

**Issue 2:**
 Type 12345, (It will display as 12,345|)
- move the cursor next to comma as 12,|345
- now type a decimal point (it will display as 12.|345), now type 82 (it will display as 12.|28345). Expected output should be 12.82|345

**Issue 3:** 
 Type 1234567 (It will display as 1,234,567|)
- keep the cursor before '5' (it will display as 1,234,|567)
- now type decimal point (it will display as 1,234.56|7) you'll notice that the cursor jumped. Expected output should be 1,234.|567

I guess, the `newStart `index is incorrect for above scenarios.

**Comment by aldoKelvianto** [comment]
Issue 3: Is a known bug.
Issue 1 & 2: Sadly, I just introduced that in the last commit.
Thanks for noticing, I'll work on it. For the time being, you can use 0.9.3

**Comment by mkaarthick** [comment]
@aldoKelvianto Ok. Thanks.
 so issue #3 can be fixed in 0.9.4?

**Comment by aldoKelvianto** [comment]
@mkaarthick Yes [in here](https://github.com/aldoKelvianto/AutoFormatEditText/issues/3), along with another improvement. Stay tuned 👌
